Modifications in yang2dsdl script operation.
- No YANG modules are parsed with -s option.
- Output of Schematron validation sent to stderr.
- Cleanup of the script and manpage.

diff --git a/trunk/bin/yang2dsdl b/trunk/bin/yang2dsdl
--- a/trunk/bin/yang2dsdl
+++ b/trunk/bin/yang2dsdl
@@ -29,9 +29,13 @@ rng_lib=${PYANG_RNG_LIBDIR:-/usr/local/share/yang/schema}/relaxng-lib.rng
 usage() {
     cat <<EOF
 
-Usage: yang2dsdl <options> <filename> ...
+Usage: 1. yang2dsdl [-t <target>] [-d <dir>] [-b <basename>] \\
+                    [-v <instance>] <module> ...
+       2. yang2dsdl [-t target] [-d <dir>] -s -b <basename> -v <instance>
+       3. yang2dsdl -h
 
-Generates DSDL schemas from YANG module(s).
+Generates DSDL schemas from YANG module(s) and validates
+instance documents.
 
 Options:
   -h             Displays this help message and exits.
@@ -46,7 +50,7 @@ Options:
                  (current directory by default).
   -v <instance>  Validates the instance document in file <instance>.
   -s             Performs just validation, without (re)generating
-                 the schemas. Only allowed together with -v.
+                 the schemas. Only allowed together with -v and -b.
 EOF
 }
 
@@ -56,11 +60,11 @@ gen_relaxng() {
 	--stringparam basename $basename \
         --stringparam target $target --stringparam rng-lib $rng_lib \
         $xslt_dir/gen-relaxng.xsl $hybs
-    [[ $? == 0 ]] || fail
+    [[ $? == 0 ]] || fail 2
     xsltproc $XSLT_OPTS --output $dir/$basename-gdefs.rng \
 	--stringparam basename $basename \
         --stringparam gdefs-only 1 $xslt_dir/gen-relaxng.xsl $hybs
-    [[ $? == 0 ]] || fail
+    [[ $? == 0 ]] || fail 2
     echo "Done."
 }
 
@@ -68,7 +72,7 @@ gen_schematron() {
     echo -e "\n== Generating Schematron schema '$btname.sch'"
     xsltproc $XSLT_OPTS --output $btname.sch \
         --stringparam target $target $xslt_dir/gen-schematron.xsl $hybs
-    [[ $? == 0 ]] || fail
+    [[ $? == 0 ]] || fail 2
     echo "Done."
 }
 
@@ -76,7 +80,7 @@ gen_dsrl() {
     echo -e "\n== Generating DSRL schema '$btname.dsrl'"
     xsltproc $XSLT_OPTS --output $btname.dsrl \
         --stringparam target $target $xslt_dir/gen-dsrl.xsl $hybs
-    [[ $? == 0 ]] || fail
+    [[ $? == 0 ]] || fail 2
     echo "Done."
 }
 
@@ -84,18 +88,19 @@ validate() {
     echo -e "\n== Validating grammar and datatypes ..."
     if [ -f $btname.rng ] ; then
         xmllint --noout --relaxng $btname.rng $instance
-	[[ $? == 0 ]] || fail
+	[[ $? == 0 ]] || fail 3
     else
-        echo "RELAX NG schema '$btname.rng' not found, skipping ..."
+        echo "RELAX NG schema '$btname.rng' not found."
+	fail 2
     fi
-    echo -e "\n== Adding default values ..."
+    echo -en "\n== Adding default values... "
     if [ -f $btname.dsrl ] ; then
         xsltproc -o $dsrlxsl $xslt_dir/dsrl2xslt.xsl $btname.dsrl
-	[[ $? == 0 ]] || fail
+	[[ $? == 0 ]] || fail 2
         xsltproc -o $instwdef $dsrlxsl $instance
-	[[ $? == 0 ]] || fail
+	[[ $? == 0 ]] || fail 3
         inst4sch=$instwdef
-        echo "Done."
+        echo -e "done."
     else
         echo "DSRL schema '$btname.dsrl' not found, no defaults added ..."
         inst4sch=$instance
@@ -105,7 +110,7 @@ validate() {
         xsltproc $xslt_dir/iso_abstract_expand.xsl $btname.sch | \
             xsltproc -o $schxsl $xslt_dir/iso_svrl_for_xslt1.xsl -
         xsltproc $schxsl $inst4sch | xsltproc $xslt_dir/svrl2text.xsl -
-	[[ $? == 0 ]] || fail
+	[[ $? == 0 ]] || fail 3
     else
         echo "Schematron schema '$btname.sch' not found, skipping ..."
     fi
@@ -115,9 +120,15 @@ cleanup () {
     rm -f $hybs $schxsl $dsrlxsl $instwdef
 }
 
+rtfm () {
+    echo 'Please check the manual page or run "yang2dsdl -h"' >&2
+    exit 1
+}
+
 fail () {
+    # Parameter is the exit code
     cleanup
-    exit 2
+    exit $1
 }
 
 while getopts ":ht:d:b:v:s" opt ; do
@@ -133,7 +144,7 @@ while getopts ":ht:d:b:v:s" opt ; do
                 && $target != "getconf-reply" && $target != "notif" ]]
             then
                 echo "Invalid argument for -t: $target."
-                exit 1
+                rtfm
             fi
             ;;
         d)
@@ -158,10 +169,11 @@ while getopts ":ht:d:b:v:s" opt ; do
             ;;
         \?)
             echo "Invalid option: -$OPTARG." >&2
-            exit 1
+            rtfm
             ;;
         :)
             echo "Option -$OPTARG requires an argument."
+	    rtfm
             ;;
     esac
 done
@@ -173,12 +185,6 @@ fi
 
 shift $(($OPTIND-1))
 yam=$*
-if [[ $yam == "" ]] ; then
-    echo "No input file given." >&2
-    usage
-    exit 1
-fi
-
 randext=$(mktemp -u .XXXXXXXX)
 hybs=$dir/dsdl$randext
 schxsl=$dir/sch$randext
@@ -186,20 +192,22 @@ dsrlxsl=$dir/dsrl$randext
 instwdef=$dir/inst$randext
 
 if [[ $noschema == "0" ]] ; then
-    if [ ! -w $dir ] ; then
+    if [[ $yam == "" ]] ; then
+	echo "No input YANG module given." >&2
+	rtfm
+    elif [ ! -w $dir ] ; then
         echo "Directory '$dir' not writable."
         exit 1
     fi
     pyang -f dsdl -o $hybs --dsdl-no-documentation \
         --dsdl-no-dublin-core $yam
-    [[ $? == 0 ]] || fail
+    [[ $? == 0 ]] || fail 2
     if [[ $basename == "" ]] ; then
         basename=$(xsltproc $xslt_dir/basename.xsl $hybs)
     fi
 elif [[ $basename == "" ]] ; then
-    basename=$(pyang -f dsdl --dsdl-no-documentation \
-        --dsdl-no-dublin-core $yam | xsltproc $xslt_dir/basename.xsl -)
-    [[ $? == 0 ]] || fail
+    echo "-b <basename> is required with -s option." >&2
+    rtfm
 fi
 
 btname=$dir/$basename-$target
@@ -208,6 +216,8 @@ if [[ $noschema == "0" ]] ; then
     gen_relaxng
     gen_schematron
     gen_dsrl
+else
+    echo "== Using pre-generated schemas"
 fi
 
 if [[ $instance != "" ]] ; then
