Many changes namely to XSLT, added Schematron implementation.

diff --git a/trunk/bin/yang2dsdl b/trunk/bin/yang2dsdl
--- a/trunk/bin/yang2dsdl
+++ b/trunk/bin/yang2dsdl
@@ -1,10 +1,11 @@
 #!/bin/bash
 
 # Defaults for arguments
-schema=rng
-target=get-reply
-dir=input
-name="_NO_NAME_"
+target="dstore"
+basename=""
+dir="."
+instance=""
+noschema=0
 
 xslt_dir=${PYANG_XSLT_DIR:-/usr/local/share/yang/xslt}
 rng_lib=${PYANG_RNG_LIBDIR:-/usr/local/share/yang/schema}/relaxng-lib.rng
@@ -14,117 +15,166 @@ usage() {
 
 Usage: yang2dsdl <options> <filename> ...
 
-Generates DSDL schemas from YANG module in <filename>.
+Generates DSDL schemas from YANG module(s).
 
 Options:
-  -h           Show this help message and exit.
-  -s <schema>  Select the schema to generate (default "rng").
-               Must be one of "rng", "sch" and "dsrl".
-  -t <target>  Specify the validation target (default "get-reply").
-               Must be one of "dstore", "get-reply", "getconf-reply",
-               "rpc" and "notif". Option -n <name> is required
-               for the latter two.
-  -n <name>    Specify the name of notification or RPC method.
-               The name has to include the standard prefix of
-               the module where the method/notification is defined.
-  -i|-o        Specify RPC request (-i) or reply (-o) (default -i).
+  -h             Displays this help message and exits.
+  -t <target>    Specifies the validation target. The argument <target>
+                 must be one of: "dstore" (default), "get-reply",
+                 "getconf-reply", "rpc", "rpc-reply" and "notif".
+  -b <basename>  Specifies the basename of files in which the output
+                 schemas are stored. The default is the concatenation
+                 of the names of all input YANG modules connected
+                 with the underscore character "_".
+  -d <dir>       Specifies the directory for output files
+                 (current directory by default).
+  -v <instance>  Validates the instance document in file <instance>.
+  -s             Performs just validation, without (re)generating
+                 the schemas. Only allowed together with -v.
 EOF
 }
 
-gen_schema() {
-    pyang -f cts --cts-no-documentation --cts-no-dublin-core $yam | \
-	xsltproc $XSLT_OPTS $extra_pars \
-	--stringparam target $target --stringparam name $name \
-	--stringparam dir $dir $xslt_dir/$stylesheet -
-}
-
 gen_relaxng() {
-    stylesheet="gen-relaxng.xsl"
-    extra_pars="--stringparam rng-lib $rng_lib"
-    gen_schema
+    echo "== Generating RELAX NG schema '$btname.rng'"
+    xsltproc $XSLT_OPTS --output $btname.rng \
+        --stringparam target $target --stringparam rng-lib $rng_lib \
+        $xslt_dir/gen-relaxng.xsl $hybs
+    xsltproc $XSLT_OPTS --output $dir/$basename-gdefs.rng \
+        --stringparam gdefs-only 1 $xslt_dir/gen-relaxng.xsl $hybs
+    echo "Done."
 }
 
 gen_schematron() {
-    stylesheet="gen-schematron.xsl"
-    extrapars=""
-    gen_schema
+    echo -e "\n== Generating Schematron schema '$btname.sch'"
+    xsltproc $XSLT_OPTS --output $btname.sch \
+        --stringparam target $target $xslt_dir/gen-schematron.xsl $hybs
+    echo "Done."
 }
 
 gen_dsrl() {
-    stylesheet="gen-dsrl.xsl"
-    extrapars=""
-    gen_schema
+    echo -e "\n== Generating DSRL schema '$btname.dsrl'"
+    xsltproc $XSLT_OPTS --output $btname.dsrl \
+        --stringparam target $target $xslt_dir/gen-dsrl.xsl $hybs
+    echo "Done."
 }
 
-while getopts ":hs:t:n:io" opt ; do
+validate() {
+    echo -e "\n== Validating grammar and datatypes ..."
+    if [ -f $btname.rng ] ; then
+        xmllint --noout --relaxng $btname.rng $instance
+    else
+        echo "RELAX NG schema '$btname.rng' not found, skipping ..."
+    fi
+    echo -e "\n== Adding default values ..."
+    if [ -f $btname.dsrl ] ; then
+        xsltproc -o $dsrlxsl $xslt_dir/dsrl2xslt.xsl $btname.dsrl
+        xsltproc -o $instwdef $dsrlxsl $instance
+        inst4sch=$instwdef
+        echo "Done."
+    else
+        echo "DSRL schema '$btname.dsrl' not found, no defaults added ..."
+        inst4sch=$instance
+    fi
+    echo -e "\n== Validating semantic constraints ..."
+    if [ -f $btname.sch ] ; then
+        xsltproc $xslt_dir/iso_abstract_expand.xsl $btname.sch | \
+            xsltproc -o $schxsl $xslt_dir/iso_svrl_for_xslt1.xsl -
+        xsltproc $schxsl $inst4sch | xsltproc $xslt_dir/svrl2text.xsl -
+    else
+        echo "Schematron schema '$btname.sch' not found, skipping ..."
+    fi
+}
+
+while getopts ":ht:d:b:v:s" opt ; do
     case $opt in
-	h)
-	    usage
-	    exit 0
-	    ;;
-	s)
-	    schema=$OPTARG
-	    ;;
-	t)
-	    target=$OPTARG
-	    if [[ $target != "dstore" && $target != "get-reply" \
-		&& $target != "rpc" \
-		&& $target != "getconf-reply" && $target != "notif" ]]
-	    then
-		echo "Invalid argument for -t: $target."
-		exit 1
-	    fi
-	    ;;
-	n)
-	    name=$OPTARG
-	    ;;
-	i)
-	    dir=input
-	    ;;
-	o)
-	    dir=output
-	    ;;
-	\?)
-	    echo "Invalid option: -$OPTARG." >&2
-	    exit 1
-	    ;;
-	:)
-	    echo "Option -$OPTARG requires an argument."
-	    ;;
+        h)
+            usage
+            exit 0
+            ;;
+        t)
+            target=$OPTARG
+            if [[ $target != "dstore" && $target != "get-reply" \
+                && $target != "rpc" && $target != "rpc-reply" \
+                && $target != "getconf-reply" && $target != "notif" ]]
+            then
+                echo "Invalid argument for -t: $target."
+                exit 1
+            fi
+            ;;
+        d)
+            dir=$OPTARG
+            if [ ! -d $dir ] ; then
+                echo "Directory '$dir' doesn't exist."
+                exit 1
+            fi
+            ;;
+        b)
+            basename=$OPTARG
+            ;;
+        v)
+            instance=$OPTARG
+            if [ ! -f $instance ] ; then
+                echo "File '$instance' not found."
+                exit 1
+            fi
+            ;;
+        s)
+            noschema=1
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG." >&2
+            exit 1
+            ;;
+        :)
+            echo "Option -$OPTARG requires an argument."
+            ;;
     esac
 done
-shift $(($OPTIND-1))
-yam=$*
-if [[ ($target == "rpc" || $target == "notif") && $name == "_NO_NAME_" ]]
-then
-    echo "Requires $target name (option -n)." >&2
+
+if [[ $noschema == "1" && $instance == "" ]] ; then
+    echo "Option -s may only be used together with -v."
     exit 1
 fi
+
+shift $(($OPTIND-1))
+yam=$*
 if [[ $yam == "" ]] ; then
     echo "No input file given." >&2
     usage
     exit 1
 fi
-for ym in $yam
-do
-    if [ ! -f $ym ] ; then
-        echo "File '$ym' not found."
+
+randext=$(mktemp -u .XXXXXXXX)
+hybs=$dir/dsdl$randext
+schxsl=$dir/sch$randext
+dsrlxsl=$dir/dsrl$randext
+instwdef=$dir/inst$randext
+
+if [[ $noschema == "0" ]] ; then
+    if [ ! -w $dir ] ; then
+        echo "Directory '$dir' not writable."
         exit 1
     fi
-done
+    pyang -f dsdl -o $hybs --dsdl-no-documentation \
+        --dsdl-no-dublin-core $yam
+    if [[ $basename == "" ]] ; then
+        basename=$(xsltproc $xslt_dir/basename.xsl $hybs)
+    fi
+elif [[ $basename == "" ]] ; then
+    basename=$(pyang -f dsdl --dsdl-no-documentation \
+        --dsdl-no-dublin-core $yam | xsltproc $xslt_dir/basename.xsl -)
+fi
 
-case $schema in
-    rng)
-	gen_relaxng
-	;;
-    sch)
-	gen_schematron
-	;;
-    dsrl)
-	gen_dsrl
-	;;
-    *)
-	echo "Invalid argument for -s: $schema."
-	exit 1
-	;;
-esac
+btname=$dir/$basename-$target
+
+if [[ $noschema == "0" ]] ; then
+    gen_relaxng
+    gen_schematron
+    gen_dsrl
+fi
+
+if [[ $instance != "" ]] ; then
+    validate
+fi
+
+# rm -f $hybs $schxsl $dsrlxsl $instwdef
